# Generated by Django 4.2.3 on 2023-08-01 04:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('accreditor', 'Accreditor')], default='accreditor', max_length=20)),
                ('accreditor_code', models.CharField(max_length=20, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=200, null=True)),
                ('expression_doc', models.FileField(upload_to='media/expression_doc', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accreditors.accreditor')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('reg_body_no', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('member', 'Member'), ('team lead', 'Team lead')], default='member', max_length=50)),
                ('profession', models.CharField(choices=[('none', 'None'), ('architect', 'Architect'), ('Town Planner', 'Town Planner'), ('structure engineer', 'Structure Engineer'), ('mechanical engineer', 'Mechanical Engineer'), ('electrical engineer', 'Electrical Engineer'), ('builder', 'Builder'), ('geoscientist', 'Geoscientist')], default='none', max_length=50)),
                ('lasrra', models.FileField(upload_to='media/lasrra', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('reg_certificate', models.FileField(upload_to='media/reg_certificate', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('curr_license', models.FileField(upload_to='media/curr_license', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('pro_certificate', models.FileField(upload_to='media/pro_certificate', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accreditors.accreditor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
    ]
