# Generated by Django 4.2.3 on 2023-08-05 13:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accreditors', '0004_alter_accreditor_category_alter_accreditor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditor',
            name='contact_address',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accreditor',
            name='contact_email',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accreditor',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='accreditor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
